version: '3'

services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      MSSQL_PID: Developer
      MSSQL_SA_PASSWORD: "Test12345@"  # Set your SQL Server password here
      ACCEPT_EULA: "Y"
    ports:
      - '1433:1433'
