name: node tests

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
    - uses: actions/checkout@v3

    - name: Start containers
      run: docker-compose -f "unitTests/docker-compose.yml" up -d --build

    - name: Use Node.js $
      uses: actions/setup-node@v3
      with:
        node-version: $
        cache: 'npm'

    - name: Install dependencies
      run: npm install
    
    - name: Run tests
      run: npm test

    - name: Stop containers
      if: always()
      run: docker-compose -f "unitTests/docker-compose.yml" down